# Railway Configuration for Sayar WhatsApp Commerce Platform
# Web API service - does NOT run the background worker
# For worker service, see railway.worker.toml

[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"
watchPatterns = ["back/**"]

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

# Custom domain configuration
# Domain: api.usesayar.com
# This will be configured in Railway dashboard

[environments.production]
variables = {
  ENV = "production",
  DEBUG = "false",
  API_HOST = "0.0.0.0",
  # Disable worker in web service (runs in separate worker service)
  WORKER_ENABLED = "false"
}

# Development environment (optional)
[environments.development]
variables = {
  ENV = "development",
  DEBUG = "true",
  API_HOST = "0.0.0.0",
  # Disable worker in web service (runs in separate worker service)
  WORKER_ENABLED = "false"
}